package com.revature.objects;

import java.util.UUID;

public class Reimbursement {

	private String REIMBURSEMENT_ID;
	private int REIMBURSEMENT_TYPE_ID;
	private double REIMBURSEMENT_REQUESTED;
	private double FINAL_REIMBURSEMENT_AMOUNT;
	private String REASON;
	
	
	public Reimbursement(){}


	/*This creates a new instance without assignning a new ID*/
	public Reimbursement(int REIMBURSEMENT_TYPE_ID, double REIMBURSEMENT_REQUESTED,
			double FINAL_REIMBURSEMENT_AMOUNT, String REASON) {
		super();
		this.REIMBURSEMENT_ID = UUID.randomUUID().toString();
		this.REIMBURSEMENT_TYPE_ID = REIMBURSEMENT_TYPE_ID;
		this.REIMBURSEMENT_REQUESTED = REIMBURSEMENT_REQUESTED;
		this.FINAL_REIMBURSEMENT_AMOUNT = FINAL_REIMBURSEMENT_AMOUNT;
		this.REASON = REASON;
	}
	
	
	/*This creates a new instance while assigning a new ID*/
	public Reimbursement(String REIMBURSEMENT_ID, int REIMBURSEMENT_TYPE_ID, double REIMBURSEMENT_REQUESTED,
			double FINAL_REIMBURSEMENT_AMOUNT, String REASON) {
		super();
		
		this.REIMBURSEMENT_ID = REIMBURSEMENT_ID; 
		this.REIMBURSEMENT_TYPE_ID = REIMBURSEMENT_TYPE_ID;
		this.REIMBURSEMENT_REQUESTED = REIMBURSEMENT_REQUESTED;
		this.FINAL_REIMBURSEMENT_AMOUNT = FINAL_REIMBURSEMENT_AMOUNT;
		this.REASON = REASON;
	}


	@Override
	public String toString() {
		return "Reimbursement [REIMBURSEMENT_ID=" + REIMBURSEMENT_ID + ", REIMBURSEMENT_TYPE_ID="
				+ REIMBURSEMENT_TYPE_ID + ", REIMBURSEMENT_REQUESTED=" + REIMBURSEMENT_REQUESTED
				+ ", FINAL_REIMBURSEMENT_AMOUNT=" + FINAL_REIMBURSEMENT_AMOUNT + ", REASON=" + REASON + "]";
	}


	public String getREIMBURSEMENT_ID() {
		return this.REIMBURSEMENT_ID;
	}


	public void setREIMBURSEMENT_ID(String rEIMBURSEMENT_ID) {
		this.REIMBURSEMENT_ID = rEIMBURSEMENT_ID;
	}


	public int getREIMBURSEMENT_TYPE_ID() {
		return this.REIMBURSEMENT_TYPE_ID;
	}


	public void setREIMBURSEMENT_TYPE_ID(int rEIMBURSEMENT_TYPE_ID) {
		this.REIMBURSEMENT_TYPE_ID = rEIMBURSEMENT_TYPE_ID;
	}


	public double getREIMBURSEMENT_REQUESTED() {
		return this.REIMBURSEMENT_REQUESTED;
	}


	public void setREIMBURSEMENT_REQUESTED(double rEIMBURSEMENT_REQUESTED) {
		this.REIMBURSEMENT_REQUESTED = rEIMBURSEMENT_REQUESTED;
	}


	public double getFINAL_REIMBURSEMENT_AMOUNT() {
		return this.FINAL_REIMBURSEMENT_AMOUNT;
	}


	public void setFINAL_REIMBURSEMENT_AMOUNT(double fINAL_REIMBURSEMENT_AMOUNT) {
		this.FINAL_REIMBURSEMENT_AMOUNT = fINAL_REIMBURSEMENT_AMOUNT;
	}


	public String getREASON() {
		return this.REASON;
	}


	public void setREASON(String rEASON) {
		this.REASON = rEASON;
	}
	
	
	
	
}
