package com.revature.objects;

public class Reimbursement_Type {

	private int REIMBURSEMENT_TYPE_ID;
	private String REIMBURSEMENT_TYPE_NAME;
	private double PERCENTAGE;
	
	public Reimbursement_Type(int rEIMBURSEMENT_TYPE_ID, String rEIMBURSEMENT_TYPE_NAME, double pERCENTAGE) {
		super();
		REIMBURSEMENT_TYPE_ID = rEIMBURSEMENT_TYPE_ID;
		REIMBURSEMENT_TYPE_NAME = rEIMBURSEMENT_TYPE_NAME;
		PERCENTAGE = pERCENTAGE;
	}

	@Override
	public String toString() {
		return "Reimbursement_Type [REIMBURSEMENT_TYPE_ID=" + REIMBURSEMENT_TYPE_ID + ", REIMBURSEMENT_TYPE_NAME="
				+ REIMBURSEMENT_TYPE_NAME + ", PERCENTAGE=" + PERCENTAGE + "]";
	}

	public int getREIMBURSEMENT_TYPE_ID() {
		return REIMBURSEMENT_TYPE_ID;
	}

	public void setREIMBURSEMENT_TYPE_ID(int rEIMBURSEMENT_TYPE_ID) {
		REIMBURSEMENT_TYPE_ID = rEIMBURSEMENT_TYPE_ID;
	}

	public String getREIMBURSEMENT_TYPE_NAME() {
		return REIMBURSEMENT_TYPE_NAME;
	}

	public void setREIMBURSEMENT_TYPE_NAME(String rEIMBURSEMENT_TYPE_NAME) {
		REIMBURSEMENT_TYPE_NAME = rEIMBURSEMENT_TYPE_NAME;
	}

	public double getPERCENTAGE() {
		return PERCENTAGE;
	}

	public void setPERCENTAGE(double pERCENTAGE) {
		PERCENTAGE = pERCENTAGE;
	}
	
	
	
}
